config/routes.rb
Rails.application.routes.draw do
  # get 'loans/new'

  resources :loans , only: [:new, :create]
  get 'books', to: 'books#index'
  
  resources :books, only: [:show]
  root 'books#index'
  post 'books' , to: 'books#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :loans

    validates :title, presence: true
    validates :author, presence: true
    validates :genre, presence: true

    enum state_book: [:en_estante,:prestado]
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :book

  validates :state_book , presence: true
  validates :user_name, presence: true

  enum state_book: [:devolucion , :prestamo]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @q = Book.ransack(params[:q])
    
    @books = @q.result(distinct: true)

  end

  def create
    @book = Book.create(title: params[:title] , author: params[:author] , genre: params[:genre])
    @book.save
  end

  def show

    @book = Book.find(params[:id].to_i)

    @loans = @book.loans

  end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @books = Book.all.order(title: :asc)
    @loans = Loan.all.order(id: :desc)
  end

  def create

    @loan = Loan.new

    if params[:state_book].to_i == 0
      @loan.returned = params[:date_loans]
    elsif params[:state_book].to_i == 1
      @loan.borrowed = params[:date_loans]
    end

    @loan.book_id = params[:books].to_i
    
    
    
    if params[:state_book].to_i == 1
      @loan.state_book = "prestamo"
    else
      @loan.state_book = "devolucion"
    end
    

    @loan.user_name = params[:user_name]

    if (@loan.book.state_book == "en_estante" && @loan.state_book == "prestamo") || (@loan.book.state_book == "prestado" && @loan.state_book == "devolucion")
      if @loan.save

        @book = @loan.book

        if @loan.state_book == "prestamo"
          @book.state_book = "prestado"
        else
          @book.state_book = "en_estante"
        end 

        @book.save

        redirect_to new_loan_path , notice: 'Loan was successfully created'
      else
        redirect_to new_loan_path , notice: 'ERROR !!!!!!!'
      end
    else
        redirect_to new_loan_path , notice: 'No es posible realizar este registro'
      
    end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/books/create.html.erb
<% if @book.errors.any? %>
 <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being
    saved:</h2>
    <ul>
        <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
 </div>
<% else %>
 <h1>Exito, Book guardado !!!! </h1>

 <p>Title : <%= @book.title %></p>   
 <p>Author : <%= @book.author %></p>   
 <p>Genre : <%= @book.genre %></p>   

 <%= link_to 'Home', books_path  %>
<% end %>

app/views/books/index.html.erb
<% if notice.present? %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>



<%= form_tag(books_path, method: "post") do %>
     <div class="form-group">
        <%= label_tag(:title, "Titulo") %>
        <%= text_field_tag(:title , nil , required: true) %>
    </div>
    <div class="form-group">
        <%= label_tag(:author, "Autor") %>
        <%= text_field_tag(:author, nil , required: true) %>
    </div>
    <div class="form-group">
        <%= label_tag(:genre, "Genero") %>
        <%= text_field_tag(:genre, nil , required: true) %>
    </div>

    <%= submit_tag("Enviar") %>
<% end %>


<%= search_form_for @q do |f| %>
  <%= f.label :state_book %>
  

  <%= f.select(:state_book_eq, options_for_select({ "En Estante" => "0", "Prestado" => "1" }),{ include_blank: true }) %>

  <%= f.submit %>
<% end %>



<table class="table table-dark">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= sort_link(@q, :title) %></th>
      <th>Author</th>
      <th>Genre</th>
      <th>State</th>
      <th>Accion</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.state_book %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h1>Libro</h1>

<p>Titulo: <%= @book.title %> </p>
<p>Autor: <%= @book.author %> </p>
<p>Genero: <%= @book.genre %> </p>
<p>Estado: <%= @book.state_book %> </p>

<%= render 'loans/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/loans/_index.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th>Book</th>
      <th>State</th>
      <th>Fecha</th>
      <th>Persona</th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= link_to loan.book.title, book_path(loan.book) %></td>
        <td><%= loan.state_book %></td>

        <% if loan.state_book == "devolucion" %>
            <td><%= loan.returned %></td>
        <% else %>
            <% if loan.borrowed.present? %>
              <td><%= loan.borrowed %> </td>
            <% end %>
        <% end %>
        
        <td><%= loan.user_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/loans/new.html.erb
<% if notice.present? %>

    <div class="alert alert-primary" role="alert">
    <%= notice %>
    </div>

<% end %>


<%= form_tag(loans_path) do  %>
    <%= label_tag 'books', "Libros"%>
    <%= select_tag "books", options_from_collection_for_select(@books, "id", "title") %>

    <%= label_tag 'state_book', "Acción"%>
    <select name="state_book">
        <option value="0">Devolucion</option>
        <option value="1">Prestamo</option>
    </select>
    
    <%= label_tag 'date_loans', "Fecha"%>
    <%= datetime_field_tag 'date_loans' , "#{Time.now.strftime("%Y-%m-%d")}T#{Time.now.strftime("%H:%M")}"%>

    <%= label_tag 'user_name', "Nombre"%>
    <%= text_field_tag 'user_name' , nil , required: true %>

    <%= submit_tag("Guardar") %>

<% end %>



<%= render 'index' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg avbar-dark bg-dark container">
        <a class="navbar-brand " href="/#">Mis libros</a>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ml-5">
              <%= link_to 'Home', books_path , class: "btn btn-secondary " %>
            </li>
            <li class="nav-item ml-5">
              <%= link_to 'Prestamo/Devolucion  ', new_loan_path, class: "btn btn-secondary " %>
            </li>
          </ul>
        
    
</nav>